-- Setup script for New AI Training Data Tables
-- Connect to the appropriate database/schema
--
-- NOTE: The AI Training Data Recorder system has been removed from the application.
-- This script is provided for historical reference only.

-- Drop existing AI training tables if they exist (for clean setup)
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE AI_USER_FEEDBACK CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE AI_FALLBACK_EVENTS CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE AI_EXECUTION_RESULTS CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE AI_SQL_PROCESSING CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE AI_RESPONSE_SELECTIONS CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE AI_MODEL_INTERACTIONS CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE AI_SCHEMA_CONTEXTS CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE AI_QUERY_CLASSIFICATIONS CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE AI_TRAINING_QUERIES CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

-- Create AI_TRAINING_QUERIES table (base table for all user queries)
CREATE TABLE AI_TRAINING_QUERIES (
    QUERY_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    USER_QUERY_TEXT CLOB,
    TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    SESSION_ID VARCHAR2(100),
    CLIENT_INFO VARCHAR2(500),
    DATABASE_TYPE VARCHAR2(50),
    QUERY_MODE VARCHAR2(50),
    USERNAME VARCHAR2(100)  -- Add username column for tracking user login
);

-- Create AI_QUERY_CLASSIFICATIONS table (query classification results)
CREATE TABLE AI_QUERY_CLASSIFICATIONS (
    CLASSIFICATION_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    QUERY_ID NUMBER REFERENCES AI_TRAINING_QUERIES(QUERY_ID),
    INTENT VARCHAR2(50),
    CONFIDENCE_SCORE NUMBER(3,2),
    COMPLEXITY_SCORE NUMBER(3,2),
    ENTITIES_JSON CLOB,
    PROCESSING_STRATEGY VARCHAR2(50),
    BUSINESS_CONTEXT CLOB,
    CLASSIFICATION_TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Create AI_SCHEMA_CONTEXTS table (retrieved schema context information)
CREATE TABLE AI_SCHEMA_CONTEXTS (
    CONTEXT_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    QUERY_ID NUMBER REFERENCES AI_TRAINING_QUERIES(QUERY_ID),
    SCHEMA_DEFINITION_JSON CLOB,
    TABLES_USED_JSON CLOB,
    COLUMN_MAPPING_JSON CLOB,
    RETRIEVAL_TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Create AI_MODEL_INTERACTIONS table (API and Local model interactions)
CREATE TABLE AI_MODEL_INTERACTIONS (
    INTERACTION_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    QUERY_ID NUMBER REFERENCES AI_TRAINING_QUERIES(QUERY_ID),
    MODEL_TYPE VARCHAR2(10), -- 'api' or 'local'
    MODEL_NAME VARCHAR2(100),
    PROVIDER VARCHAR2(50),
    PROMPT_TEXT CLOB,
    RESPONSE_TEXT CLOB,
    RESPONSE_TIME_MS NUMBER,
    TOKEN_COUNT NUMBER,
    CONFIDENCE_SCORE NUMBER(3,2),
    STATUS VARCHAR2(20), -- 'success', 'timeout', 'error', 'failed'
    ERROR_MESSAGE CLOB,
    COST_USD NUMBER,
    INTERACTION_TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Create AI_RESPONSE_SELECTIONS table (model response selection decisions)
CREATE TABLE AI_RESPONSE_SELECTIONS (
    SELECTION_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    QUERY_ID NUMBER REFERENCES AI_TRAINING_QUERIES(QUERY_ID),
    SELECTED_MODEL_TYPE VARCHAR2(10), -- 'api' or 'local'
    SELECTION_CRITERIA_JSON CLOB,
    SCORE_COMPARISON_JSON CLOB,
    FINAL_RESPONSE_TEXT CLOB,
    SELECTION_REASONING CLOB,
    SELECTION_TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Create AI_SQL_PROCESSING table (SQL validation and processing)
CREATE TABLE AI_SQL_PROCESSING (
    PROCESSING_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    QUERY_ID NUMBER REFERENCES AI_TRAINING_QUERIES(QUERY_ID),
    EXTRACTED_SQL CLOB,
    VALIDATION_STATUS VARCHAR2(20),
    VALIDATION_ERRORS_JSON CLOB,
    OPTIMIZATION_SUGGESTIONS_JSON CLOB,
    FINAL_SQL CLOB,
    PROCESSING_TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Create AI_EXECUTION_RESULTS table (SQL execution results)
CREATE TABLE AI_EXECUTION_RESULTS (
    RESULT_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    QUERY_ID NUMBER REFERENCES AI_TRAINING_QUERIES(QUERY_ID),
    EXECUTION_STATUS VARCHAR2(20),
    EXECUTION_TIME_MS NUMBER,
    ROW_COUNT NUMBER,
    RESULT_DATA_JSON CLOB,
    ERROR_MESSAGE CLOB,
    EXECUTION_TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Create AI_FALLBACK_EVENTS table (fallback scenario tracking)
CREATE TABLE AI_FALLBACK_EVENTS (
    EVENT_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    QUERY_ID NUMBER REFERENCES AI_TRAINING_QUERIES(QUERY_ID),
    TRIGGER_REASON VARCHAR2(100),
    FALLBACK_MODEL_TYPE VARCHAR2(10), -- 'api' or 'local'
    FALLBACK_RESPONSE_TEXT CLOB,
    RECOVERY_STATUS VARCHAR2(20),
    EVENT_TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Create AI_USER_FEEDBACK table (user feedback on responses)
CREATE TABLE AI_USER_FEEDBACK (
    FEEDBACK_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    QUERY_ID NUMBER REFERENCES AI_TRAINING_QUERIES(QUERY_ID),
    FEEDBACK_TYPE VARCHAR2(20), -- 'good', 'wrong', 'needs_improvement'
    FEEDBACK_SCORE NUMBER(1,0), -- 1-5 scale
    FEEDBACK_COMMENT CLOB,
    SOURCE VARCHAR2(10), -- 'api' or 'local'
    SUBMISSION_TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Create indexes for better query performance
CREATE INDEX IDX_TRAINING_QUERIES_TIMESTAMP ON AI_TRAINING_QUERIES(TIMESTAMP);
CREATE INDEX IDX_QUERY_CLASSIFICATIONS_QUERY_ID ON AI_QUERY_CLASSIFICATIONS(QUERY_ID);
CREATE INDEX IDX_SCHEMA_CONTEXTS_QUERY_ID ON AI_SCHEMA_CONTEXTS(QUERY_ID);
CREATE INDEX IDX_MODEL_INTERACTIONS_QUERY_ID ON AI_MODEL_INTERACTIONS(QUERY_ID);
CREATE INDEX IDX_RESPONSE_SELECTIONS_QUERY_ID ON AI_RESPONSE_SELECTIONS(QUERY_ID);
CREATE INDEX IDX_SQL_PROCESSING_QUERY_ID ON AI_SQL_PROCESSING(QUERY_ID);
CREATE INDEX IDX_EXECUTION_RESULTS_QUERY_ID ON AI_EXECUTION_RESULTS(QUERY_ID);
CREATE INDEX IDX_FALLBACK_EVENTS_QUERY_ID ON AI_FALLBACK_EVENTS(QUERY_ID);
CREATE INDEX IDX_USER_FEEDBACK_QUERY_ID ON AI_USER_FEEDBACK(QUERY_ID);

-- Verify tables were created
SELECT table_name FROM user_tables WHERE table_name LIKE 'AI_%' ORDER BY table_name;