# ERP R12 SQL Generator
# Dedicated module for generating SQL queries for ERP R12 data

import logging
import re
from typing import Dict, List, Optional, Any
from app.ERP_R12_Test_DB.vector_store_chroma import search_similar_schema

logger = logging.getLogger(__name__)

class ERPSqlGenerator:
    """
    Dedicated SQL generator for ERP R12 queries.
    This class now acts as a coordinator for API-based SQL generation rather than generating SQL locally.
    """
    
    def __init__(self):
        # This class no longer generates SQL locally
        pass
    
    def generate_sql(self, user_query: str, selected_db: str = "source_db_2") -> str:
        """
        Coordinate SQL generation for ERP R12 based on user input.
        This method no longer generates SQL locally but returns a placeholder
        that indicates SQL should be generated by API models.
        
        Args:
            user_query: The user's natural language query
            selected_db: The database ID to query
            
        Returns:
            Placeholder string indicating API-based SQL generation is required
        """
        try:
            logger.info(f"Coordinating SQL generation for ERP query: {user_query}")
            logger.info("SQL generation should be handled by API models as per requirements")
            
            # Return a placeholder that indicates this should be handled by API models
            return "API_BASED_SQL_GENERATION_REQUIRED"
            
        except Exception as e:
            logger.error(f"Failed to coordinate SQL generation: {e}", exc_info=True)
            return "API_BASED_SQL_GENERATION_REQUIRED"
    
    def get_schema_context_for_api(self, user_query: str, selected_db: str) -> List[Dict]:
        """
        Get schema context for the user query to be used by API models.
        
        Args:
            user_query: The user's natural language query
            selected_db: The database ID to query
            
        Returns:
            List of schema documents
        """
        try:
            schema_docs = search_similar_schema(user_query, selected_db, top_k=10)
            return schema_docs
        except Exception as e:
            logger.warning(f"Failed to get schema context: {e}")
            return []

# Global instance
erp_sql_generator = ERPSqlGenerator()

